yarnPath: .yarn/releases/yarn-4.7.0.cjs
nodeLinker: node-modules
enableGlobalCache: false

compressionLevel: mixed

enableTelemetry: false

logFilters:
  - code: YN0002 # MISSING_PEER_DEPENDENCY
    level: discard
  - code: YN0060 # INCOMPATIBLE_PEER_DEPENDENCY
    level: discard
